name: prod
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.5.0"
      - name: yarn
        run: yarn
      - name: install
        run: yarn install 
      - name: build
        run: yarn build
      - name: copy file  via ssh key
        uses: appleboy/scp-action@master
        with:
          source: "antdpro-demo/*"
          host: ${{ secrets.HOST }}
          target: "/usr/src/zhoubichuan/prod/"
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
